### ISSUE TITLE
Integration with schroot-formula broken

### ISSUE THREAD

**Issue by philpep** [saltstack-formulas/sbuild-formula#3]
Hi,

I've this error while using sbuild-formula with https://github.com/umeboshi2/schroot-formula:

```
Jinja variable the template 'schroot/state.jinja' (imported on line 4) does not export the requested name 'schroot_guess_overlay_fs'
```

I guess a fork of schroot-formula exist but is not publicly available.

**Comment by philpep** [comment]
Fixed by hardcoding `overlay` as `overlay_fs` variable. I think it depend on the kernel version right ?

**Comment by rhertzog** [comment]
The correct git repository for schroot-formula is this one: https://github.com/saltstack-formulas/schroot-formula/ (the "forked from umeboshi2/schroot-formula" is completely bogus, it was forked from a repository of mine that I dropped and github somehow invented a new origin to the fork).

Do you also have the problem with this git repository?

**Comment by rhertzog** [comment]
And yes, it depends on what modules are built for the kernel (aufs vs overlay).

**Comment by philpep** [comment]
Oh didn't notice this repository, thanks!
